### Data Collection: 
#### Solbiato Kids

In [78]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import glob
import os
import time

In [24]:
#Direct Feed Url 
url = "https://solbiatosport.com/product-category/solbiato-kids/feed/"

In [25]:
page_number = 1
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=1
✅ Success! Found 10 products on Page 1.

,product_name,category,price,description_raw,url
0,K-TOORA,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-toora/
1,K-WARD,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-ward/
2,K-TITANIC,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-titanic/
3,K-BLOSSOM,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-blossom/
4,K-SHOOKA,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-shooka/
5,K-AJAR,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-ajar/
6,K-STAMP,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-stamp/
7,K-ZEPHYR,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-zephyr/
8,K-JACK,Kids,N/A,French Terry Jogger,https://solbiatosport.com/product/k-jack/
9,K-QUADRANT,Kids,N/A,Nylon Shorts,https://solbiatosport.com/product/k-quadrant/

💾 Saved to: ../data/raw/kids_page_1_raw.csv

In [28]:
page_number = 2 
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=2
✅ Success! Found 10 products on Page 2.

,product_name,category,price,description_raw,url
0,K-CL-French Terry Sweat Top,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-cl-french-...
1,K-KAVIR,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-kavir/
2,K-CL-HOODIE TEE,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-cl-hoodie-...
3,K-CL-SLIPPY BULL TEE,Kids,N/A,Slippy Short Sleeve T-Shirt,https://solbiatosport.com/product/k-cl-slippy-...
4,K-ROCKY COLORS,Kids,N/A,French Terry Zip-Neck Sweat Top,https://solbiatosport.com/product/k-rocky-colors/
5,K-CL-French Terry Jogger,Kids,N/A,French Terry Joggers,https://solbiatosport.com/product/k-cl-jogger/
6,K-BLENDER,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-blender/
7,K-BAY BRIDGE,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-bay-bridge/
8,K-GOOSE,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-goose/
9,K-EXIT,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-exit/

💾 Saved to: ../data/raw/kids_page_2_raw.csv

In [29]:
page_number = 3 
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=3
✅ Success! Found 10 products on Page 3.

,product_name,category,price,description_raw,url
0,K-FARYAD,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-faryad/
1,K-HOWEY,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-howey/
2,K-ABJAD,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-abjad/
3,K-SMILEY,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-smiley/
4,K-DAVAR,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-davar/
5,K-BLEACHY,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-bleachy/
6,K-TRAVERSE,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-traverse/
7,K-LOWW,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-loww/
8,K-J.B.,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-j-b/
9,K-PARTICULAR,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-particular/

💾 Saved to: ../data/raw/kids_page_3_raw.csv

In [30]:
page_number = 4
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=4
✅ Success! Found 10 products on Page 4.

,product_name,category,price,description_raw,url
0,K-CONDO,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-condo/
1,K-KINDER,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-kinder/
2,K-AURA,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-aura/
3,K-SHOKO,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-shoko/
4,K-KOOO,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-kooo/
5,K-SEDAA,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-sedaa/
6,K-SCIENCE,Kids,N/A,French Terry Joggers,https://solbiatosport.com/product/k-science/
7,K-KAYY,Kids,N/A,French Terry Joggers,https://solbiatosport.com/product/k-kayy/
8,K-BAROON,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-baroon/
9,K-YASARI,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-yasari/

💾 Saved to: ../data/raw/kids_page_4_raw.csv

In [31]:
page_number = 5 
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=5
✅ Success! Found 10 products on Page 5.

,product_name,category,price,description_raw,url
0,K-ZANG,Kids,N/A,Regular Fleece Hoodie Sweat Top,https://solbiatosport.com/product/k-zang/
1,K-SINGLATO,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-singlato/
2,K-WASHED,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-washed/
3,K-PERPERI,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-perperi/
4,K-REJECT,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-reject/
5,K-PARTNER,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-partner/
6,K-NEW YORK,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-new-york/
7,K-OPPA,Kids,N/A,Noah Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-oppa/
8,K-NAKON,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-nakon/
9,K-MEDI,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-medi/

💾 Saved to: ../data/raw/kids_page_5_raw.csv

In [32]:
page_number = 6
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=6
✅ Success! Found 10 products on Page 6.

,product_name,category,price,description_raw,url
0,K-AMIN,Kids,N/A,Techno Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-amin/
1,K-ANAHEIM,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-anaheim/
2,K-BOVEM,Kids,N/A,Techno Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-bovem/
3,K-CONE,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-cone/
4,K-DOCTRINE,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-doctrine/
5,K-EISA,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-eisa/
6,K-GASHT,Kids,N/A,French Terry Joggers,https://solbiatosport.com/product/k-gasht/
7,K-HOME,Kids,N/A,Noah Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-home/
8,K-LAANG,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-laang/
9,K-LAPORTA,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-laporta/

💾 Saved to: ../data/raw/kids_page_6_raw.csv

In [33]:
page_number = 7 
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=7
✅ Success! Found 10 products on Page 7.

,product_name,category,price,description_raw,url
0,K-LASH,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-lash/
1,K-LOUBAT,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-loubat/
2,K-MATESTO,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-matesto/
3,K-MARD,Kids,N/A,Noah Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-mard/
4,K-PATOO,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-patoo/
5,K-KIAN,Kids,N/A,Regular Fleece Hoodie Sweat Top,https://solbiatosport.com/product/k-kian/
6,K-JULY,Kids,N/A,French Terry Shorts,https://solbiatosport.com/product/k-july/
7,K-KAMMAL,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-kammal/
8,K-WEX,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-wex/
9,K-SATURDAY,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-saturday/

💾 Saved to: ../data/raw/kids_page_7_raw.csv

In [34]:
page_number = 8 
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=8
✅ Success! Found 10 products on Page 8.

,product_name,category,price,description_raw,url
0,K-TEXT,Kids,N/A,Nylon Shorts,https://solbiatosport.com/product/k-text/
1,K-SAAIL,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-saail/
2,K-THURSDAY,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-thursday/
3,K-MONOLITH,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-monolith/
4,K-CLOTH,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-cloth/
5,K-RESTON,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-reston/
6,K-CONGRESS,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-congress/
7,K-ABSTRACT,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-abstract/
8,K-WAVED,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-waved/
9,K-POINTY,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-pointy/

💾 Saved to: ../data/raw/kids_page_8_raw.csv

In [35]:
page_number = 9 
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=9
✅ Success! Found 10 products on Page 9.

,product_name,category,price,description_raw,url
0,K-CODDY,Kids,N/A,Nylon Shorts,https://solbiatosport.com/product/k-coddy/
1,K-RODDY,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-roddy/
2,K-YETA,Kids,N/A,French Terry Shorts,https://solbiatosport.com/product/k-yeta/
3,K-VACIATO,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-vaciato/
4,K-MADA,Kids,N/A,French Terry Joggers,https://solbiatosport.com/product/k-mada/
5,K-MEESH,Kids,N/A,French Terry Joggers,https://solbiatosport.com/product/k-meesh/
6,K-ADIYELA,Kids,N/A,French Terry Joggers,https://solbiatosport.com/product/k-adiyela/
7,K-ADDA,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-adda/
8,K-ESMO,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-esmo/
9,K-NESFO,Kids,N/A,Techno Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-nesfo/

💾 Saved to: ../data/raw/kids_page_9_raw.csv

In [36]:
page_number = 10 
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=10
✅ Success! Found 10 products on Page 10.

,product_name,category,price,description_raw,url
0,K-BAFFLE,Kids,N/A,Techno Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-baffle/
1,K-AMMAN,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-amman/
2,K-FLAMES,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-flames/
3,K-DRAGON,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-dragon/
4,K-HAARF,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-haarf/
5,K-NEMO,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-nemo/
6,K-LEYDEE,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-leydee/
7,K-AZADI,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-azadi/
8,K-RETRO,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-retro/
9,K-MIMOSHA,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-mimosha/

💾 Saved to: ../data/raw/kids_page_10_raw.csv

In [37]:
page_number = 11 
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=11
✅ Success! Found 10 products on Page 11.

,product_name,category,price,description_raw,url
0,K-CARRIER,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-carrier/
1,K-ZERO,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-zero/
2,K-BEHBOOD,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-behbood/
3,K-NEW-D,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-new-d/
4,K-AMSTERDAM,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-amsterdam/
5,K-JOSE,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-jose/
6,K-NISTI,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-nisti/
7,K-GOOLD,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-goold/
8,K-BOWL,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-bowl/
9,K-LEAGUE,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-league/

💾 Saved to: ../data/raw/kids_page_11_raw.csv

In [38]:
page_number = 12 
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=12
✅ Success! Found 10 products on Page 12.

,product_name,category,price,description_raw,url
0,K-DIVAN,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-divan/
1,K-TUB,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-tub/
2,K-NAAN,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-naan/
3,K-YOOZ,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-yooz/
4,K-ROOSTA,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-roosta/
5,K-BIDO,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-bido/
6,K-ALEXIS,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-alexis/
7,K-LOOS,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-loos/
8,K-ARMAN,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-arman/
9,K-ATISH,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-atish/

💾 Saved to: ../data/raw/kids_page_12_raw.csv

In [39]:
page_number = 13
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=13
✅ Success! Found 10 products on Page 13.

,product_name,category,price,description_raw,url
0,K-STEEPS,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-steeps/
1,K-JAKE,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-jake/
2,K-BEGOO,Kids,N/A,Regular Fleece Hoodie Sweat Top,https://solbiatosport.com/product/k-begoo/
3,K-QIN,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-qin/
4,K-SHOULDERS,Kids,N/A,Noah Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-shoulders/
5,K-FULSHEAR,Kids,N/A,Regular Fleece Hoodie Sweat Top,https://solbiatosport.com/product/k-fulshear/
6,K-ARZESH,Kids,N/A,Noah Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-arzesh/
7,K-PAXX,Kids,N/A,Noah Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-paxx/
8,K-HAWA,Kids,N/A,Noah Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-hawa/
9,K-HOYA,Kids,N/A,Noah Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-hoya/

💾 Saved to: ../data/raw/kids_page_13_raw.csv

In [40]:
page_number = 14 
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=14
✅ Success! Found 10 products on Page 14.

,product_name,category,price,description_raw,url
0,K-VANTAGE,Kids,N/A,Techno Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-vantage/
1,K-BLOCKED,Kids,N/A,Techno Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-blocked/
2,K-TAMANA,Kids,N/A,Techno Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-tamana/
3,K-VISTA,Kids,N/A,French Terry Joggers,https://solbiatosport.com/product/k-vista/
4,K-ZEMIN,Kids,N/A,Noah Fabric Joggers,https://solbiatosport.com/product/k-zemin/
5,K-CL-French Terry Tape Logo Hoodie,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-cl-french-...
6,K-CL-French Terry Tape Logo Joggers,Kids,N/A,French Terry Joggers,https://solbiatosport.com/product/k-cl-french-...
7,K-CL-French Terry Full-Zip Hoodie,Kids,N/A,French Terry Full-Zip Hoodie,https://solbiatosport.com/product/k-cl-full-zi...
8,K-MONUMENT,Kids,N/A,Nylon Shorts,https://solbiatosport.com/product/k-monument/
9,K-MORE,Kids,N/A,Nylon Shorts,https://solbiatosport.com/product/k-more/

💾 Saved to: ../data/raw/kids_page_14_raw.csv

In [41]:
page_number = 15 
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=15
✅ Success! Found 10 products on Page 15.

,product_name,category,price,description_raw,url
0,K-VERTEX,Kids,N/A,French Terry Shorts,https://solbiatosport.com/product/k-vertex/
1,K-SHIMA,Kids,N/A,French Terry Shorts,https://solbiatosport.com/product/k-shima/
2,K-MAASH,Kids,N/A,Nylon Shorts,https://solbiatosport.com/product/k-maash/
3,K-DIGITS,Kids,N/A,French Terry Joggers,https://solbiatosport.com/product/k-digits/
4,K-VILIDGE,Kids,N/A,French Terry Joggers,https://solbiatosport.com/product/k-vilidge/
5,K-SARI,Kids,N/A,Techno Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-sari/
6,K-HARBOR,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-harbor/
7,K-NETTING,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-netting/
8,K-REPTOWN,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-reptown/
9,K-NICHO,Kids,N/A,Techno Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-nicho/

💾 Saved to: ../data/raw/kids_page_15_raw.csv

In [42]:
page_number = 16 
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=16
✅ Success! Found 10 products on Page 16.

,product_name,category,price,description_raw,url
0,K-BOLTED,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-bolted/
1,K-YAZD,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-yazd/
2,K-TEMPLE,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-temple/
3,K-SUNSHINE,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-sunshine/
4,K-SPAC,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-spac/
5,K-MELLAT,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-mellat/
6,K-ICYROAD,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-icyroad/
7,K-HAASH,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-haash/
8,K-TECK,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-teck/
9,K-EXPRESS,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-express/

💾 Saved to: ../data/raw/kids_page_16_raw.csv

In [43]:
page_number = 17 
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=17
✅ Success! Found 10 products on Page 17.

,product_name,category,price,description_raw,url
0,K-DANIEL,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-daniel/
1,K-YAAS,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-yaas/
2,K-REFLECTION,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-reflection/
3,K-FARAZ,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-faraz/
4,K-CURTIN,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-curtin/
5,K-CHAPEL,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-chapel/
6,K-GAATI,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-gaati/
7,K-SHELL,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-shell/
8,K-NICK,Kids,N/A,Cotton Lycra Hoodie T-Shirt\r\n\r\n&#160;,https://solbiatosport.com/product/k-nick/
9,K-KAZAW,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-kazaw/

💾 Saved to: ../data/raw/kids_page_17_raw.csv

In [44]:
page_number = 18 
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=18
✅ Success! Found 10 products on Page 18.

,product_name,category,price,description_raw,url
0,K-DOUGLAS,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-douglas/
1,K-FOSTER,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-foster/
2,K-TRIANGLE,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-triangle/
3,K-LOLLIPOP,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-lollipop/
4,K-TORNADO,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-tornado/
5,K-VISA,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-visa/
6,K-TANGERINE,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-tangerine/
7,K-SEPTEMBER,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-september/
8,K-TRIBE,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-tribe/
9,K-TERMINATE,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-terminate/

💾 Saved to: ../data/raw/kids_page_18_raw.csv

In [45]:
page_number = 19 
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=19
✅ Success! Found 10 products on Page 19.

,product_name,category,price,description_raw,url
0,K-DARAK,Kids,N/A,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/k-darak/
1,K-ZIPPING,Kids,N/A,Noah Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-zipping/
2,K-ROOF,Kids,N/A,Noah Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-roof/
3,K-EARTH,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-earth/
4,K-DETOUR,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-detour/
5,K-DIAMONDER,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-diamonder/
6,K-REQUEST,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-request/
7,K-CAMPING,Kids,N/A,Techno Fabric Hoodie Sweat Top,https://solbiatosport.com/product/k-camping/
8,K-TYPICAL,Kids,N/A,French Terry Hoodie Sweat Top,https://solbiatosport.com/product/k-typical/
9,K-PARALLEL,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-parallel/

💾 Saved to: ../data/raw/kids_page_19_raw.csv

In [46]:
page_number = 20 
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=20
✅ Success! Found 10 products on Page 20.

,product_name,category,price,description_raw,url
0,K-OSHIN,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-oshin/
1,K-AFSOON,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-afsoon/
2,K-SPIDER,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-spider/
3,K-DOVE,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-dove/
4,K-LIVANA,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-livana/
5,K-TURK,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-turk/
6,K-DIGI,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-digi/
7,K-KARAT,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-karat/
8,K-RAHA,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-raha/
9,K-MARRS,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-marrs/

💾 Saved to: ../data/raw/kids_page_20_raw.csv

In [47]:
page_number = 21 
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=21
✅ Success! Found 10 products on Page 21.

,product_name,category,price,description_raw,url
0,K-FOXX,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-foxx/
1,K-INVISIBLE (Full Zip),Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-invisible/
2,K-CRACKED,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-cracked/
3,K-DOMAIN,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-domain/
4,K-BIRTHDAY,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-birthday/
5,K-ISLE,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-isle/
6,K-MIROOR,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-miroor/
7,K-SPEAKER,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-speaker/
8,K-DIRR,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-dirr/
9,K-HIGHWAY,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-highway/

💾 Saved to: ../data/raw/kids_page_21_raw.csv

In [48]:
page_number = 22 
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=22
✅ Success! Found 1 products on Page 22.

,product_name,category,price,description_raw,url
0,K-BACKPACK,Kids,N/A,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/k-backpack/

💾 Saved to: ../data/raw/kids_page_22_raw.csv

In [49]:
page_number = 23 
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-kids/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Kids data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    kids_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        
        # Pulling the raw description which contains the price and material
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        kids_products.append({
            'product_name': name,
            'category': 'Kids',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_kids = pd.DataFrame(kids_products)
    print(f"✅ Success! Found {len(df_kids)} products on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_kids)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/kids_page_{page_number}_raw.csv'
    df_kids.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Kids data from: https://solbiatosport.com/product-category/solbiato-kids/feed/?paged=23
✅ Success! Found 0 products on Page 23.

Empty DataFrame
Columns: []
Index: []

💾 Saved to: ../data/raw/kids_page_23_raw.csv

In [ ]:
import glob
import os

#Merging all Solbiato Kids Files 

# 1. Be very specific about the path
# If you are in the 'notebooks' folder, we go up one level then into 'data/raw'
path = '../data/raw/'
all_files = glob.glob(os.path.join(path, "kids_page_*_raw.csv"))

li = []

print(f"Checking {len(all_files)} files...")

for filename in all_files:
    try:
        # We try to read it; if it's empty, it will jump to the 'except' part
        df = pd.read_csv(filename)
        if not df.empty:
            li.append(df)import pandas as pd
            # print(f"Added: {os.path.basename(filename)}")
    except pd.errors.EmptyDataError:
        print(f"Skipping empty file: {os.path.basename(filename)}")
    except Exception as e:
        print(f"Error reading {os.path.basename(filename)}: {e}")

# 2. The Final Stack
if li:
    df_kids_final = pd.concat(li, axis=0, ignore_index=True)
    df_kids_final.drop_duplicates(inplace=True)
    
    output_path = '../data/raw/solbiato_kids_COMPLETE.csv'
    df_kids_final.to_csv(output_path, index=False)
    
    print(f"\n✅ SUCCESS!")
    print(f"Merged {len(li)} files into {output_path}")
    print(f"Total Products: {len(df_kids_final)}")
else:
    print("\n❌ No valid data found in any of the files.")

Checking 23 files...
Skipping empty file: kids_page_23_raw.csv

✅ SUCCESS!
Merged 22 files into ../data/raw/solbiato_kids_COMPLETE.csv
Total Products: 211

#### Accessories

In [65]:
#Direct Feed Url 
url = "https://solbiatosport.com/product-category/accessories/feed/"

In [69]:
page_number = 1
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-sport/sport-accessories/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Accessories data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    accessories_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        accessories_products.append({
            'product_name': name,
            'category': 'Accessories',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_acc = pd.DataFrame(accessories_products)
    print(f"✅ Success! Found {len(df_acc)} accessories on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_acc)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/accessories_page_{page_number}_raw.csv'
    df_acc.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Accessories data from: https://solbiatosport.com/product-category/solbiato-sport/sport-accessories/feed/?paged=1
✅ Success! Found 10 accessories on Page 1.

,product_name,category,price,description_raw,url
0,PURE,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/pure/
1,NORTHWEST,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/northwest/
2,PASHA,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/pasha/
3,MARKED,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/marked/
4,ROSE,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/rose/
5,ROOPA,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/roopa/
6,ELEVEN,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/eleven/
7,ROOKA,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/rooka/
8,TRAP,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/trap/
9,PIAAZ,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/piaaz/

💾 Saved to: ../data/raw/accessories_page_1_raw.csv

In [70]:
page_number = 2
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-sport/sport-accessories/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Accessories data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    accessories_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        accessories_products.append({
            'product_name': name,
            'category': 'Accessories',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_acc = pd.DataFrame(accessories_products)
    print(f"✅ Success! Found {len(df_acc)} accessories on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_acc)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/accessories_page_{page_number}_raw.csv'
    df_acc.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Accessories data from: https://solbiatosport.com/product-category/solbiato-sport/sport-accessories/feed/?paged=2
✅ Success! Found 10 accessories on Page 2.

,product_name,category,price,description_raw,url
0,KILID,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/kilid/
1,LAYUP,Accessories,N/A,<p>Cotton Lycra Skull Cap</p>,https://solbiatosport.com/product/layup/
2,NAIROBI,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/nairobi/
3,RASOO,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/rasoo/
4,BEEM,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/beem/
5,CHINCHIN,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/chinchin/
6,COVER,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/cover/
7,KEMI,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/kemi/
8,FASTER,Accessories,N/A,Skully,https://solbiatosport.com/product/faster/
9,PATTONI,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/pattoni/

💾 Saved to: ../data/raw/accessories_page_2_raw.csv

In [71]:
page_number = 3
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-sport/sport-accessories/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Accessories data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    accessories_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        accessories_products.append({
            'product_name': name,
            'category': 'Accessories',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_acc = pd.DataFrame(accessories_products)
    print(f"✅ Success! Found {len(df_acc)} accessories on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_acc)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/accessories_page_{page_number}_raw.csv'
    df_acc.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Accessories data from: https://solbiatosport.com/product-category/solbiato-sport/sport-accessories/feed/?paged=3
✅ Success! Found 10 accessories on Page 3.

,product_name,category,price,description_raw,url
0,NODDY,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/noddy/
1,REFLECTIVE,Accessories,N/A,Lanyard Keychain,https://solbiatosport.com/product/reflective/
2,NEW CLASSIC,Accessories,N/A,Lanyard Keychain,https://solbiatosport.com/product/new-classic-2/
3,CLASSIC,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/classic-2/
4,HOBB,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/hobb/
5,VOLA,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/vola/
6,L.T.,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/l-t/
7,RAJA,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/raja/
8,ODD1,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/odd1/
9,TELO,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/telo/

💾 Saved to: ../data/raw/accessories_page_3_raw.csv

In [72]:
page_number = 4
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-sport/sport-accessories/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Accessories data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    accessories_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        accessories_products.append({
            'product_name': name,
            'category': 'Accessories',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_acc = pd.DataFrame(accessories_products)
    print(f"✅ Success! Found {len(df_acc)} accessories on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_acc)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/accessories_page_{page_number}_raw.csv'
    df_acc.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Accessories data from: https://solbiatosport.com/product-category/solbiato-sport/sport-accessories/feed/?paged=4
✅ Success! Found 10 accessories on Page 4.

,product_name,category,price,description_raw,url
0,TOTO,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/toto/
1,BUSAN,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/busan/
2,TREAT,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/treat/
3,MOOSA,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/moosa/
4,RAANG,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/raang/
5,JAVAD,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/javad/
6,HAZY,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/hazy/
7,COBALT,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/cobalt/
8,CUPP,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/cupp/
9,VELLO,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/vello/

💾 Saved to: ../data/raw/accessories_page_4_raw.csv

In [73]:
page_number = 5
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-sport/sport-accessories/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Accessories data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    accessories_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        accessories_products.append({
            'product_name': name,
            'category': 'Accessories',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_acc = pd.DataFrame(accessories_products)
    print(f"✅ Success! Found {len(df_acc)} accessories on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_acc)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/accessories_page_{page_number}_raw.csv'
    df_acc.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Accessories data from: https://solbiatosport.com/product-category/solbiato-sport/sport-accessories/feed/?paged=5
✅ Success! Found 10 accessories on Page 5.

,product_name,category,price,description_raw,url
0,MORNING,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/morning/
1,ZARF,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/zarf/
2,FARIBA,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/fariba/
3,PILLAR,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/pillar/
4,DISTRACT,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/distract/
5,SL-TIP,Accessories,N/A,100% Wool Hat with Stripe,https://solbiatosport.com/product/sl-tip/
6,SL-TAP,Accessories,N/A,100% Wool Hat,https://solbiatosport.com/product/sl-tap/
7,NEUTRAL BOXER BRIEFS,Accessories,N/A,Cotton Stretch Boxer Briefs,https://solbiatosport.com/product/neutral-boxe...
8,PLUS1,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/plus1/
9,TIPIC,Accessories,N/A,Cotton Lycra Skull Cap,https://solbiatosport.com/product/tipic/

💾 Saved to: ../data/raw/accessories_page_5_raw.csv

In [74]:
page_number = 6
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-sport/sport-accessories/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Accessories data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    accessories_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        accessories_products.append({
            'product_name': name,
            'category': 'Accessories',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_acc = pd.DataFrame(accessories_products)
    print(f"✅ Success! Found {len(df_acc)} accessories on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_acc)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/accessories_page_{page_number}_raw.csv'
    df_acc.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Accessories data from: https://solbiatosport.com/product-category/solbiato-sport/sport-accessories/feed/?paged=6
✅ Success! Found 10 accessories on Page 6.

,product_name,category,price,description_raw,url
0,BULL,Accessories,N/A,,https://solbiatosport.com/product/bull/
1,FLASH,Accessories,N/A,,https://solbiatosport.com/product/flash/
2,LASER,Accessories,N/A,,https://solbiatosport.com/product/laser/
3,BANK,Accessories,N/A,,https://solbiatosport.com/product/bank/
4,SOLBIATO RETURN,Accessories,N/A,Cotton Lycra Head Band,https://solbiatosport.com/product/solbiato-ret...
5,Solbiato Band,Accessories,N/A,Cotton Lycra Headband,https://solbiatosport.com/product/solbiato-band/
6,Solbiato Final,Accessories,N/A,Cotton Lycra Head Band,https://solbiatosport.com/product/solbiato-final/
7,Sidelogo Boxers,Accessories,N/A,Cotton Boxer-Briefs,https://solbiatosport.com/product/sidelogo-box...
8,Colorful Boxers,Accessories,N/A,,https://solbiatosport.com/product/colorful-box...
9,Socks Model #4,Accessories,N/A,,https://solbiatosport.com/product/socks-model-4/

💾 Saved to: ../data/raw/accessories_page_6_raw.csv

In [75]:
page_number = 7
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-sport/sport-accessories/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Accessories data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    accessories_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        accessories_products.append({
            'product_name': name,
            'category': 'Accessories',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_acc = pd.DataFrame(accessories_products)
    print(f"✅ Success! Found {len(df_acc)} accessories on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_acc)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/accessories_page_{page_number}_raw.csv'
    df_acc.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Accessories data from: https://solbiatosport.com/product-category/solbiato-sport/sport-accessories/feed/?paged=7
✅ Success! Found 1 accessories on Page 7.

,product_name,category,price,description_raw,url
0,Socks Model #1,Accessories,N/A,,https://solbiatosport.com/product/socks-model-1/

💾 Saved to: ../data/raw/accessories_page_7_raw.csv

In [76]:
page_number = 8
domain = "https://solbiatosport.com/"
path = f"product-category/solbiato-sport/sport-accessories/feed/?paged={page_number}"
url = domain + path

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'}

print(f"🚀 Pulling Accessories data from: {url}")
response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    accessories_products = []
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        desc = item.find('description').text if item.find('description') else "N/A"
        
        # --- NEW: Cleaning the price ---
        # This looks for a '$' followed by digits and decimals
        price_match = re.search(r'\$\d+(?:\.\d+)?', desc)
        clean_price = price_match.group(0) if price_match else "N/A"
        
        accessories_products.append({
            'product_name': name,
            'category': 'Accessories',
            'price': clean_price,
            'description_raw': desc,
            'url': link
        })
    
    # Create the DataFrame
    df_acc = pd.DataFrame(accessories_products)
    print(f"✅ Success! Found {len(df_acc)} accessories on Page {page_number}.")
    
    # Display the first few rows to verify the clean prices
    display(df_acc)
    
    # Save to your raw folder - using the page number in the filename
    file_path = f'../data/raw/accessories_page_{page_number}_raw.csv'
    df_acc.to_csv(file_path, index=False)
    print(f"💾 Saved to: {file_path}")

else:
    print(f"❌ Failed to reach site. Status Code: {response.status_code}")

🚀 Pulling Accessories data from: https://solbiatosport.com/product-category/solbiato-sport/sport-accessories/feed/?paged=8
✅ Success! Found 0 accessories on Page 8.

Empty DataFrame
Columns: []
Index: []

💾 Saved to: ../data/raw/accessories_page_8_raw.csv

In [77]:
#Merging All Accessories Files

import glob
import os

# 1. Be very specific about the path
# If you are in the 'notebooks' folder, we go up one level then into 'data/raw'
path = '../data/raw/'
all_files = glob.glob(os.path.join(path, "accessories_page_*_raw.csv"))

li = []

print(f"Checking {len(all_files)} files...")

for filename in all_files:
    try:
        # We try to read it; if it's empty, it will jump to the 'except' part
        df = pd.read_csv(filename)
        if not df.empty:
            li.append(df)
            # print(f"Added: {os.path.basename(filename)}")
    except pd.errors.EmptyDataError:
        print(f"Skipping empty file: {os.path.basename(filename)}")
    except Exception as e:
        print(f"Error reading {os.path.basename(filename)}: {e}")

# 2. The Final Stack
if li:
    df_accessories_final = pd.concat(li, axis=0, ignore_index=True)
    df_accessories_final.drop_duplicates(inplace=True)
    
    output_path = '../data/raw/solbiato_accessories_COMPLETE.csv'
    df_accessories_final.to_csv(output_path, index=False)
    
    print(f"\n✅ SUCCESS!")
    print(f"Merged {len(li)} files into {output_path}")
    print(f"Total Products: {len(df_accessories_final)}")
else:
    print("\n❌ No valid data found in any of the files.")

Checking 8 files...
Skipping empty file: accessories_page_8_raw.csv

✅ SUCCESS!
Merged 7 files into ../data/raw/solbiato_accessories_COMPLETE.csv
Total Products: 61

#### Solbiato Sport (Core/Unisex) Collection

In [83]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

In [91]:
# 1. SETTINGS
category_name = "Sport-Tops" 
# This is the EXACT full URL with the 'feed' included
base_feed_url = "https://solbiatosport.com/product-category/solbiato-sport/sport-tops/feed/"

# 2. THE AUTOMATED LOOP
all_products = []
current_page = 1

while True:
    # We add ?paged= to the end of the full feed URL
    url = f"{base_feed_url}?paged={current_page}"
    print(f"🕵️ Scraping {category_name}: Page {current_page}...")
    
    headers = {'User-Agent': 'Mozilla/5.0'}
    response = requests.get(url, headers=headers)
    
    # Stop if the page doesn't exist
    if response.status_code != 200:
        print(f"🏁 Reached the end at Page {current_page - 1}.")
        break
        
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    # Stop if no items are found
    if not items:
        print(f"🏁 No more products found after Page {current_page - 1}.")
        break
        
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        desc = item.find('description').text if item.find('description') else "N/A"
        
        all_products.append({
            'product_name': name,
            'category': category_name,
            'description_raw': desc,
            'url': link
        })
    
    current_page += 1
    time.sleep(1) # Be polite to the server!

# 3. SAVE THE MASTER FILE
df_tops_master = pd.DataFrame(all_products)
output_path = "../data/raw/solbiato_tops_COMPLETE.csv"
df_tops_master.to_csv(output_path, index=False)

print(f"\n✅ DONE! Collected {len(df_tops_master)} total Tops.")
display(df_tops_master.head())

🕵️ Scraping Sport-Tops: Page 1...
🕵️ Scraping Sport-Tops: Page 2...
🕵️ Scraping Sport-Tops: Page 3...
🕵️ Scraping Sport-Tops: Page 4...
🕵️ Scraping Sport-Tops: Page 5...
🕵️ Scraping Sport-Tops: Page 6...
🕵️ Scraping Sport-Tops: Page 7...
🕵️ Scraping Sport-Tops: Page 8...
🕵️ Scraping Sport-Tops: Page 9...
🕵️ Scraping Sport-Tops: Page 10...
🕵️ Scraping Sport-Tops: Page 11...
🕵️ Scraping Sport-Tops: Page 12...
🕵️ Scraping Sport-Tops: Page 13...
🕵️ Scraping Sport-Tops: Page 14...
🕵️ Scraping Sport-Tops: Page 15...
🕵️ Scraping Sport-Tops: Page 16...
🕵️ Scraping Sport-Tops: Page 17...
🕵️ Scraping Sport-Tops: Page 18...
🕵️ Scraping Sport-Tops: Page 19...
🕵️ Scraping Sport-Tops: Page 20...
🕵️ Scraping Sport-Tops: Page 21...
🕵️ Scraping Sport-Tops: Page 22...
🕵️ Scraping Sport-Tops: Page 23...
🕵️ Scraping Sport-Tops: Page 24...
🕵️ Scraping Sport-Tops: Page 25...
🕵️ Scraping Sport-Tops: Page 26...
🕵️ Scraping Sport-Tops: Page 27...
🕵️ Scraping Sport-Tops: Page 28...
🏁 No more products found after Page 27.

✅ DONE! Collected 263 total Tops.

,product_name,category,description_raw,url
0,SL-NIVA,Sport-Tops,Cotton Lycra Short Sleeve Polo,https://solbiatosport.com/product/sl-niva/
1,GULF,Sport-Tops,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/gulf/
2,JETTA,Sport-Tops,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/jetta/
3,WARD,Sport-Tops,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/ward/
4,KOOSHA,Sport-Tops,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/koosha/

In [93]:
#Verifying Data
print("Dataset Overview")
df_tops_master.info()

print("First 5 Items:")
display(df_tops_master.head())

print("Last 5 Items:")
display(df_tops_master.tail())

Dataset Overview
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263 entries, 0 to 262
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   product_name     263 non-null    object
 1   category         263 non-null    object
 2   description_raw  263 non-null    object
 3   url              263 non-null    object
dtypes: object(4)
memory usage: 8.3+ KB
First 5 Items:

,product_name,category,description_raw,url
0,SL-NIVA,Sport-Tops,Cotton Lycra Short Sleeve Polo,https://solbiatosport.com/product/sl-niva/
1,GULF,Sport-Tops,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/gulf/
2,JETTA,Sport-Tops,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/jetta/
3,WARD,Sport-Tops,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/ward/
4,KOOSHA,Sport-Tops,Cotton Lycra Short Sleeve T-Shirt,https://solbiatosport.com/product/koosha/

Last 5 Items:

,product_name,category,description_raw,url
258,SPEAKER,Sport-Tops,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/speaker/
259,BACKPACK,Sport-Tops,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/backpack/
260,HIGHWAY,Sport-Tops,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/highway/
261,SOPHIA,Sport-Tops,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/sophia/
262,DARIAN,Sport-Tops,Cotton Lycra Hoodie T-Shirt,https://solbiatosport.com/product/darian/

In [94]:
# 1. SETTINGS
category_name = "Sport-Bottoms" 
# This is the EXACT full URL with the 'feed' included
base_feed_url = "https://solbiatosport.com/product-category/solbiato-sport/sport-bottoms/feed/"

# 2. THE AUTOMATED LOOP
all_products = []
current_page = 1

while True:
    # We add ?paged= to the end of the full feed URL
    url = f"{base_feed_url}?paged={current_page}"
    print(f"🕵️ Scraping {category_name}: Page {current_page}...")
    
    headers = {'User-Agent': 'Mozilla/5.0'}
    response = requests.get(url, headers=headers)
    
    # Stop if the page doesn't exist
    if response.status_code != 200:
        print(f"🏁 Reached the end at Page {current_page - 1}.")
        break
        
    soup = BeautifulSoup(response.content, 'xml')
    items = soup.find_all('item')
    
    # Stop if no items are found
    if not items:
        print(f"🏁 No more products found after Page {current_page - 1}.")
        break
        
    for item in items:
        name = item.find('title').text
        link = item.find('link').text
        desc = item.find('description').text if item.find('description') else "N/A"
        
        all_products.append({
            'product_name': name,
            'category': category_name,
            'description_raw': desc,
            'url': link
        })
    
    current_page += 1
    time.sleep(1) # Be polite to the server!

# 3. SAVE THE MASTER FILE
df_bottoms_master = pd.DataFrame(all_products)
output_path = "../data/raw/solbiato_bottoms_COMPLETE.csv"
df_bottoms_master.to_csv(output_path, index=False)

print(f"\n✅ DONE! Collected {len(df_bottoms_master)} total Bottoms.")
display(df_bottoms_master.head())

🕵️ Scraping Sport-Bottoms: Page 1...
🕵️ Scraping Sport-Bottoms: Page 2...
🕵️ Scraping Sport-Bottoms: Page 3...
🕵️ Scraping Sport-Bottoms: Page 4...
🕵️ Scraping Sport-Bottoms: Page 5...
🕵️ Scraping Sport-Bottoms: Page 6...
🕵️ Scraping Sport-Bottoms: Page 7...
🕵️ Scraping Sport-Bottoms: Page 8...
🕵️ Scraping Sport-Bottoms: Page 9...
🕵️ Scraping Sport-Bottoms: Page 10...
🕵️ Scraping Sport-Bottoms: Page 11...
🕵️ Scraping Sport-Bottoms: Page 12...
🕵️ Scraping Sport-Bottoms: Page 13...
🕵️ Scraping Sport-Bottoms: Page 14...
🕵️ Scraping Sport-Bottoms: Page 15...
🕵️ Scraping Sport-Bottoms: Page 16...
🕵️ Scraping Sport-Bottoms: Page 17...
🕵️ Scraping Sport-Bottoms: Page 18...
🕵️ Scraping Sport-Bottoms: Page 19...
🕵️ Scraping Sport-Bottoms: Page 20...
🕵️ Scraping Sport-Bottoms: Page 21...
🕵️ Scraping Sport-Bottoms: Page 22...
🕵️ Scraping Sport-Bottoms: Page 23...
🕵️ Scraping Sport-Bottoms: Page 24...
🏁 No more products found after Page 23.

✅ DONE! Collected 227 total Bottoms.

,product_name,category,description_raw,url
0,COMPASS,Sport-Bottoms,French Terry Jogger,https://solbiatosport.com/product/compass/
1,JACK,Sport-Bottoms,French Terry Jogger,https://solbiatosport.com/product/jack/
2,ACT,Sport-Bottoms,French Terry Jogger,https://solbiatosport.com/product/act/
3,WAYS,Sport-Bottoms,French Terry Jogger,https://solbiatosport.com/product/ways/
4,CHAPAR,Sport-Bottoms,French Terry Jogger,https://solbiatosport.com/product/chapar/

In [95]:
#Verifying Data
print("Dataset Overview")
df_bottoms_master.info()

print("First 5 Items:")
display(df_bottoms_master.head())

print("Last 5 Items:")
display(df_bottoms_master.tail())

Dataset Overview
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   product_name     227 non-null    object
 1   category         227 non-null    object
 2   description_raw  227 non-null    object
 3   url              227 non-null    object
dtypes: object(4)
memory usage: 7.2+ KB
First 5 Items:

,product_name,category,description_raw,url
0,COMPASS,Sport-Bottoms,French Terry Jogger,https://solbiatosport.com/product/compass/
1,JACK,Sport-Bottoms,French Terry Jogger,https://solbiatosport.com/product/jack/
2,ACT,Sport-Bottoms,French Terry Jogger,https://solbiatosport.com/product/act/
3,WAYS,Sport-Bottoms,French Terry Jogger,https://solbiatosport.com/product/ways/
4,CHAPAR,Sport-Bottoms,French Terry Jogger,https://solbiatosport.com/product/chapar/

Last 5 Items:

,product_name,category,description_raw,url
222,YARD,Sport-Bottoms,French Terry Joggers,https://solbiatosport.com/product/yard/
223,POOYAN,Sport-Bottoms,French Terry Joggers,https://solbiatosport.com/product/pooyan/
224,LOREN,Sport-Bottoms,French Terry Joggers,https://solbiatosport.com/product/loren/
225,DOWNGRADE,Sport-Bottoms,French Terry Joggers,https://solbiatosport.com/product/downgrade/
226,BOY,Sport-Bottoms,French Terry Joggers,https://solbiatosport.com/product/boy/

#### Merging All Solbiato Products

In [96]:
import pandas as pd
import os

# 1. Define your 4 complete files
path = '../data/raw/'
files = [
    'solbiato_kids_COMPLETE.csv',
    'solbiato_accessories_COMPLETE.csv',
    'solbiato_tops_COMPLETE.csv',
    'solbiato_bottoms_COMPLETE.csv'
]

# 2. The "Big Stack"
li = []
for f in files:
    full_path = os.path.join(path, f)
    if os.path.exists(full_path):
        df = pd.read_csv(full_path)
        li.append(df)
        print(f"✅ Added {f} ({len(df)} items)")

# 3. Create the 'Source of Truth'
df_master_total = pd.concat(li, ignore_index=True)
df_master_total.drop_duplicates(inplace=True)

# 4. Save the Final Output
final_output = '../data/raw/solbiato_PROJECT_MASTER_TOTAL.csv'
df_master_total.to_csv(final_output, index=False)

print(f"\n🏆 MISSION COMPLETE! 🏆")
print(f"Grand Total Inventory: {len(df_master_total)} products")
print(f"Your project's 'Source of Truth' is saved at: {final_output}")
display(df_master_total.tail())

✅ Added solbiato_kids_COMPLETE.csv (211 items)
✅ Added solbiato_accessories_COMPLETE.csv (61 items)
✅ Added solbiato_tops_COMPLETE.csv (263 items)
✅ Added solbiato_bottoms_COMPLETE.csv (227 items)

🏆 MISSION COMPLETE! 🏆
Grand Total Inventory: 761 products
Your project's 'Source of Truth' is saved at: ../data/raw/solbiato_PROJECT_MASTER_TOTAL.csv

,product_name,category,price,description_raw,url
757,YARD,Sport-Bottoms,NaN,French Terry Joggers,https://solbiatosport.com/product/yard/
758,POOYAN,Sport-Bottoms,NaN,French Terry Joggers,https://solbiatosport.com/product/pooyan/
759,LOREN,Sport-Bottoms,NaN,French Terry Joggers,https://solbiatosport.com/product/loren/
760,DOWNGRADE,Sport-Bottoms,NaN,French Terry Joggers,https://solbiatosport.com/product/downgrade/
761,BOY,Sport-Bottoms,NaN,French Terry Joggers,https://solbiatosport.com/product/boy/

#### Pricing

In [98]:
import requests
from bs4 import BeautifulSoup

# Let's test the very first product URL
test_url = df_master_total['url'].iloc[0] 
print(f"🕵️ Attempting to snatch price from: {test_url}")

headers = {'User-Agent': 'Mozilla/5.0'}
response = requests.get(test_url, headers=headers)
soup = BeautifulSoup(response.content, 'html.parser')

# Using the EXACT class you found in the Inspect tool!
price_element = soup.find('span', class_='woocommerce-Price-amount')

if price_element:
    print(f"💰 SUCCESS! The price is: {price_element.get_text()}")
else:
    print("❌ Hmm, still can't find it. The 'Inspect' class might be inside a different tag.")

🕵️ Attempting to snatch price from: https://solbiatosport.com/product/k-darak/
💰 SUCCESS! The price is: $0.00

In [99]:
# --- THE PRECISION PRICE SNATCHER ---
import requests
from bs4 import BeautifulSoup

# Testing on your first item
test_url = df_master_total['url'].iloc[0]
print(f"🕵️ Target acquired: {test_url}")

headers = {'User-Agent': 'Mozilla/5.0'}
response = requests.get(test_url, headers=headers)
soup = BeautifulSoup(response.content, 'html.parser')

# We target the 'price' paragraph first
price_container = soup.find('p', class_='price')

if price_container:
    # .get_text() acts just like the 'innerText' you found in Inspect!
    final_price = price_container.get_text(strip=True)
    print(f"💰 SUCCESS! Captured Price: {final_price}")
else:
    # Backup: Look for any bdi tag (the one in your screenshot)
    bdi_tag = soup.find('bdi')
    if bdi_tag:
        print(f"💰 SUCCESS (BDI): {bdi_tag.get_text(strip=True)}")
    else:
        print("❌ Price still hiding. We might need a slightly different approach.")

🕵️ Target acquired: https://solbiatosport.com/product/k-darak/
💰 SUCCESS! Captured Price: $135.00Original price was: $135.00.$29.00Current price is: $29.00.

In [101]:
# --- THE SURGICAL PRICE SNATCHER ---
import requests
from bs4 import BeautifulSoup

# We'll use the K-Darak URL you just found
test_url = "https://solbiatosport.com/product/k-darak/"
print(f"🕵️ Target acquired: {test_url}")

headers = {'User-Agent': 'Mozilla/5.0'}
response = requests.get(test_url, headers=headers)
soup = BeautifulSoup(response.content, 'html.parser')

# 1. Look for the 'price' container
price_container = soup.find('p', class_='price')

if price_container:
    # 2. Find ALL price tags inside it
    all_prices = price_container.find_all('bdi')
    
    if len(all_prices) > 1:
        # If there are two prices, the LAST one is always the Sale Price
        final_price = all_prices[-1].get_text(strip=True)
        print(f"🔥 SALE PRICE FOUND: {final_price}")
    else:
        # If there's only one, that's the regular price
        final_price = all_prices[0].get_text(strip=True)
        print(f"💰 REGULAR PRICE: {final_price}")
else:
    print("❌ Price tag not found.")

🕵️ Target acquired: https://solbiatosport.com/product/k-darak/
🔥 SALE PRICE FOUND: $29.00

In [102]:
import time

# 1. We'll test a small batch of 10 first to make sure it's smooth
test_df = df_master_total.head(10).copy()

print(f"🚀 Starting Price Hunt for {len(test_df)} items...")

for index, row in test_df.iterrows():
    url = row['url']
    headers = {'User-Agent': 'Mozilla/5.0'}
    
    try:
        response = requests.get(url, headers=headers, timeout=10)
        soup = BeautifulSoup(response.content, 'html.parser')
        
        price_container = soup.find('p', class_='price')
        if price_container:
            all_prices = price_container.find_all('bdi')
            # Grab the last price (handles sales!)
            final_price = all_prices[-1].get_text(strip=True)
            test_df.at[index, 'price'] = final_price
            print(f"✅ {row['product_name']}: {final_price}")
        
        time.sleep(1) # Be polite to the site
    except:
        print(f"❌ Skipped: {row['product_name']}")

display(test_df[['product_name', 'price']].head())

🚀 Starting Price Hunt for 10 items...

/var/folders/sb/qbz1r19j2g16419q9t_gt4dr0000gn/T/ipykernel_17627/3696830219.py:21: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '$29.00' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  test_df.at[index, 'price'] = final_price

✅ K-DARAK: $29.00
✅ K-ZIPPING: $39.00
✅ K-ROOF: $34.00
✅ K-EARTH: $39.00
✅ K-DETOUR: $34.00
✅ K-DIAMONDER: $39.00
✅ K-REQUEST: $34.00
✅ K-CAMPING: $34.00
✅ K-TYPICAL: $39.00
✅ K-PARALLEL: $29.00

  product_name   price
0      K-DARAK  $29.00
1    K-ZIPPING  $39.00
2       K-ROOF  $34.00
3      K-EARTH  $39.00
4     K-DETOUR  $34.00

In [103]:
import time

# 1. We use the full master list this time!
df_final_project = df_master_total.copy()
total_items = len(df_final_project)

print(f"🚀 STARTING THE GRAND PRICE HUNT ({total_items} items)")
print("--------------------------------------------------")

for index, row in df_final_project.iterrows():
    # Only scrape if the price is missing (NaN) or empty
    if pd.isna(row['price']) or row['price'] == "N/A":
        url = row['url']
        headers = {'User-Agent': 'Mozilla/5.0'}
        
        try:
            response = requests.get(url, headers=headers, timeout=10)
            soup = BeautifulSoup(response.content, 'html.parser')
            
            price_container = soup.find('p', class_='price')
            if price_container:
                all_prices = price_container.find_all('bdi')
                # Grabs the last price in the list (handles sales!)
                final_price = all_prices[-1].get_text(strip=True)
                df_final_project.at[index, 'price'] = final_price
        except:
            pass # Keep going even if one fails
            
    # Progress update every 50 items
    if (index + 1) % 50 == 0:
        print(f"✅ Processed {index + 1} / {total_items}...")
        
    time.sleep(1) # Being polite to the site!

# 2. SAVE THE FINAL GOLDEN FILE
master_output = '../data/raw/solbiato_TOTAL_inventory_WITH_PRICES.csv'
df_final_project.to_csv(master_output, index=False)

print("\n🏆 MISSION ACCOMPLISHED! 🏆")
print(f"Total Products Processed: {total_items}")
print(f"Grand Master File Saved: {master_output}")

🚀 STARTING THE GRAND PRICE HUNT (761 items)
--------------------------------------------------

/var/folders/sb/qbz1r19j2g16419q9t_gt4dr0000gn/T/ipykernel_17627/1893796383.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '$29.00' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_final_project.at[index, 'price'] = final_price

✅ Processed 50 / 761...
✅ Processed 100 / 761...
✅ Processed 150 / 761...
✅ Processed 200 / 761...
✅ Processed 250 / 761...
✅ Processed 300 / 761...
✅ Processed 350 / 761...
✅ Processed 400 / 761...
✅ Processed 450 / 761...
✅ Processed 500 / 761...
✅ Processed 550 / 761...
✅ Processed 600 / 761...
✅ Processed 650 / 761...
✅ Processed 700 / 761...
✅ Processed 750 / 761...

🏆 MISSION ACCOMPLISHED! 🏆
Total Products Processed: 761
Grand Master File Saved: ../data/raw/solbiato_TOTAL_inventory_WITH_PRICES.csv

In [104]:
#### Sanitizing my Prices

# 1. Clean the price (Remove $ and commas)
df_final_project['price_numeric'] = df_final_project['price'].str.replace('$', '', regex=False).str.replace(',', '', regex=False)

# 2. Turn it into a real number (float)
df_final_project['price_numeric'] = pd.to_numeric(df_final_project['price_numeric'], errors='coerce')

# 3. Show the result to confirm it worked
print("✅ PRICES ARE NOW NUMBERS! Check the new 'price_numeric' column:")
display(df_final_project[['product_name', 'price', 'price_numeric']].head())

✅ PRICES ARE NOW NUMBERS! Check the new 'price_numeric' column:

  product_name   price  price_numeric
0      K-DARAK  $29.00           29.0
1    K-ZIPPING  $39.00           39.0
2       K-ROOF  $34.00           34.0
3      K-EARTH  $39.00           39.0
4     K-DETOUR  $34.00           34.0

In [105]:
print(f"Total Store Value:${df_final_project['price_numeric'].sum():,.2f}")

Total Store Value:$47,189.00